# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: ""
metadata:
  name: 'learning-paths-plugin'
  description: "Learning Paths plugin"
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
spec:

  # (Required) This can be a group(`group:<group_name>` or a user(`user:<github_username>`)
  owner: ""

  # (Required) Acceptable Type Values: service, website, library
  type: ''

  # (Required) Acceptable Lifecycle Values: experimental, production, deprecated
  lifecycle: 'experimental'

  # (Optional) The value can be the name of any known component.
  subcomponentOf: '<name_of_a_component>'

  # (Optional) An array of different components or resources.
  dependsOn:
  - '<component_or_resource>'
  - '<another_component_or_resource>'
