# Generated by Django 4.2.13 on 2024-11-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0004_auto_20240207_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathstep',
            name='weight',
            field=models.FloatField(default=1.0, help_text="Weight of this course in the learning path's aggregate grade."),
        ),
        migrations.CreateModel(
            name='LearningPathGradingCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_threshold', models.FloatField(default=100.0, help_text='Completion percentage threshold for this learning path.')),
                ('expected_grade', models.FloatField(default=75.0, help_text='Minimum average grade required to pass this learning path.')),
                ('learning_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_criteria', to='learning_paths.learningpath')),
            ],
        ),
    ]
