# Generated by Django 4.2.10 on 2024-03-01 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_auto_20230808_0944'),
        ('learning_paths', '0004_auto_20240207_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathCourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=9)),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courseenrollment')),
                ('learning_path_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_paths.learningpathenrollment')),
            ],
            options={
                'unique_together': {('learning_path_enrollment', 'course_key')},
            },
        ),
    ]
