# Generated by Django 4.2.13 on 2024-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0005_learningpathstep_weight_learningpathgradingcriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathstep',
            name='weight',
            field=models.FloatField(default=1.0, help_text="Weight of this course in the learning path's aggregate grade.Specify as a floating point number between 0 and 1, where 1 represents 100%."),
        ),
    ]
