# Generated by Django 4.2.16 on 2024-11-28 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0006_alter_learningpathstep_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathstep',
            name='weight',
            field=models.FloatField(default=1.0, help_text="Weight of this course in the learning path's aggregate grade.Specify as a floating point number between 0 and 1, where 1 represents 100%.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
