# Generated by Django 4.2.16 on 2024-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0007_alter_learningpathstep_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpathgradingcriteria',
            name='completion_threshold',
        ),
        migrations.RemoveField(
            model_name='learningpathgradingcriteria',
            name='expected_grade',
        ),
        migrations.AddField(
            model_name='learningpathgradingcriteria',
            name='required_completion',
            field=models.FloatField(default=100.0, help_text='The minimum average completion percentage across all steps in the learning path required to mark it as completed.'),
        ),
        migrations.AddField(
            model_name='learningpathgradingcriteria',
            name='required_grade',
            field=models.FloatField(default=0.75, help_text='Minimum weighted arithmetic mean grade (0.0-1.0) required across all steps to pass this learning path. The weight of each step is determined by its `weight` field.'),
        ),
    ]
